### ISSUE TITLE
About key of chord

### ISSUE THREAD

**Issue by Sodayeyeye** [Cyan0731/MusiConGen#4]
When you specify a chord in your code, what does the key look like? Is it the default C major?

**Comment by Cyan0731** [comment]
yes, it is default C major.

**Comment by Sodayeyeye** [comment]
Thank you for your reply. I have two more questions
1. Can I set the key?
2. As for the text, I would like to know if there is a general list of instruments, because I find that some instruments are not very good. Do you have any good suggestions on the writing of text content? There are some texts that I get musical representation that is not very good.
Thank you again for your patient reply and best wishes

**Comment by Cyan0731** [comment]
1. Sorry this model cannot change the key. You can only use common chords shared with C key.
2. The dataset is comprised mainly of guitar, bass and drums . So generally, these instruments have best performace in prompting.
